export const GET_SALE_DETAIL = "GET_SALE_DETAIL";
export const CREATE_SALE_DETAIL = "CREATE_SALE_DETAIL";
export const DELETE_SALE_DETAIL = "DELETE_SALE_DETAIL";
export const GET_SALE_DETAILS_REQUEST = "GET_SALE_DETAILS_REQUEST";
export const GET_SALE_DETAILS_SUCCESS = "GET_SALE_DETAILS_SUCCESS";
export const GET_SALE_DETAILS_FAILURE = "GET_SALE_DETAILS_FAILURE";
